### ISSUE TITLE
How to show a menu only on a specific li > class?

### ISSUE THREAD

**Issue by IProudNoob** [sindresorhus/electron-context-menu#110] opened 2020-06-29 15:03 UTC
Hello!!!
I have **ul>li** list and I wanted to show the menu only **li>class** and get **id li element**?

THX!!!

**Comment by sindresorhus** [comment] 2020-06-29 17:44
Duplicate of https://github.com/sindresorhus/electron-context-menu/issues/102

**Comment by sindresorhus** [comment] 2020-06-29 17:44
Not possible at the moment. Open an Electron issue.

**Closed by sindresorhus** 2020-06-29 17:44 UTC
